combined for all three OSes

diff --git a/.github/workflows/python-server-and-desktop-app-deploy.yml b/.github/workflows/python-server-and-desktop-app-deploy.yml
--- a/.github/workflows/python-server-and-desktop-app-deploy.yml
+++ b/.github/workflows/python-server-and-desktop-app-deploy.yml
@@ -10,13 +10,22 @@ jobs:
   build_desktop:
     strategy:
       matrix:
-        os: [macos-latest] # [ubuntu-latest, macos-latest, windows-latest, macos-13]
+        os: [ubuntu-latest, windows-latest, macos-latest] # [ubuntu-latest, macos-latest, windows-latest, macos-13]
     runs-on: ${{matrix.os}}
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-########### PYTHON SERVER COMPILATION STARTS HERE ###########
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2.19.0
+        with:
+          channel: stable
+
+      - name: Clean Flutter Project
+        run: flutter clean
+        working-directory: flutter_app
+
+      ########### PYTHON SERVER COMPILATION STARTS HERE ###########
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -28,20 +37,6 @@ jobs:
           mkdir -p ./flutter_app/assets/
         shell: bash
         working-directory: .
-
-      - name: Install Development Certificate for Mac
-        if: matrix.os == 'macos-latest'
-        env:
-          MAC_CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
-          MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
-        run: |
-          echo "$MAC_CERTIFICATE" | base64 --decode > dev_cert.p12
-          file dev_cert.p12
-          security create-keychain -p "temp_password" build.keychain
-          security default-keychain -s build.keychain
-          security unlock-keychain -p "temp_password" build.keychain
-          security import dev_cert.p12 -k build.keychain -P "$MAC_CERTIFICATE_PASSWORD" -T /usr/bin/codesign || (echo "Certificate import failed" && exit 1)
-          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
 
       - name: Install Linux Dependencies
         if: matrix.os == 'ubuntu-latest'
@@ -155,15 +150,18 @@ jobs:
         working-directory: .
 
 ########### FLUTTER APP COMPILATION STARTS HERE ###########
-
-      - name: Setup Flutter
-        uses: subosito/flutter-action@v2.19.0
-        with:
-          channel: stable
-
-      - name: Clean Flutter Project
-        run: flutter clean
-        working-directory: flutter_app
+      - name: Install Development Certificate for Mac
+        if: matrix.os == 'macos-latest'
+        env:
+          MAC_CERTIFICATE: ${{ secrets.MAC_CERTIFICATE }}
+          MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
+        run: |
+          echo "$MAC_CERTIFICATE" | base64 --decode > dev_cert.p12
+          security create-keychain -p "temp_password" build.keychain
+          security default-keychain -s build.keychain
+          security unlock-keychain -p "temp_password" build.keychain
+          security import dev_cert.p12 -k build.keychain -P "$MAC_CERTIFICATE_PASSWORD" -T /usr/bin/codesign || (echo "Certificate import failed" && exit 1)
+          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
 
       - name: Install Flutter Dependencies
         run: flutter pub get
