updated position to speed things up

diff --git a/.github/workflows/python-server-and-desktop-app-deploy.yml b/.github/workflows/python-server-and-desktop-app-deploy.yml
--- a/.github/workflows/python-server-and-desktop-app-deploy.yml
+++ b/.github/workflows/python-server-and-desktop-app-deploy.yml
@@ -29,6 +29,16 @@ jobs:
         shell: bash
         working-directory: .
 
+      - name: Install Development Certificate for Mac
+        if: matrix.os == 'macos-latest'
+        run: |
+          echo "$MAC_CERTIFICATE" | base64 --decode > dev_cert.p12
+          security create-keychain -p "temp_password" build.keychain
+          security default-keychain -s build.keychain
+          security unlock-keychain -p "temp_password" build.keychain
+          security import dev_cert.p12 -k build.keychain -P "$MAC_CERTIFICATE_PASSWORD" -T /usr/bin/codesign || (echo "Certificate import failed" && exit 1)
+          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
+
       - name: Install Linux Dependencies
         if: matrix.os == 'ubuntu-latest'
         run: |
@@ -141,15 +151,6 @@ jobs:
         working-directory: .
 
 ########### FLUTTER APP COMPILATION STARTS HERE ###########
-      - name: Install Development Certificate for Mac
-        if: matrix.os == 'macos-latest'
-        run: |
-          echo "$MAC_CERTIFICATE" | base64 --decode > dev_cert.p12
-          security create-keychain -p "temp_password" build.keychain
-          security default-keychain -s build.keychain
-          security unlock-keychain -p "temp_password" build.keychain
-          security import dev_cert.p12 -k build.keychain -P "$MAC_CERTIFICATE_PASSWORD" -T /usr/bin/codesign || (echo "Certificate import failed" && exit 1)
-          security set-key-partition-list -S apple-tool:,apple: -s -k "temp_password" build.keychain
 
       - name: Setup Flutter
         uses: subosito/flutter-action@v2.19.0
